### ISSUE TITLE
Get rid of reliance on separate icons file?

### ISSUE THREAD

**Issue by Reklino** [Swimlane/angular-data-table#26]
It would be nice if there was no reliance on a separate icons css file. Since the only thing icons are used for at the moment is the sort (that I know of) maybe you could just use pseudo selectors to do the job like so:

``` css
.icon-down {
    position: relative;
    left: 10px;
    &:after {
        content: '';
        position: absolute;
        display: block;
        width: 10px;
        height: 1px;
        background: gray;
        transform: rotate(45deg) translateX(-5px);
    }
    &:before {
        content: '';
        position: absolute;
        display: block;
        width: 10px;
        height: 1px;
        background: gray;
        transform: rotate(-45deg) translateX(5px);
    }
}
.icon-up {
    position: relative;
    left: 10px; top: -8px;
    &:after {
        content: '';
        position: absolute;
        display: block;
        width: 10px;
        height: 1px;
        background: gray;
        transform: rotate(-45deg) translateX(-5px);
    }
    &:before {
        content: '';
        position: absolute;
        display: block;
        width: 10px;
        height: 1px;
        background: gray;
        transform: rotate(45deg) translateX(5px);
    }
}
```

I can submit a PR if you want. Just let me know.
